=== therpraveenkumar/assessment_zoho/MickeyShopProject/AdventNetMickeyLite/AdventNet/MickeyLite/webapps/iam/conf/zsecpii-info.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="pii-detector">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="piis"></xs:element>
				<xs:element ref="models"></xs:element>
				<xs:element ref="regexes"></xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="models">
		<xs:complexType>
			<xs:choice maxOccurs="unbounded">
				<xs:element ref="model"></xs:element>
			</xs:choice>
		</xs:complexType>
	</xs:element>

	<xs:element name="model">
		<xs:complexType>
			<xs:attribute name="name" type="xs:string" use="required"></xs:attribute>
			<xs:attribute name="model-type" type="type" use="required"></xs:attribute>
			<xs:attribute name="class-name" type="xs:string" use="required"></xs:attribute>
		</xs:complexType>
	</xs:element>


	<xs:element name="piis">
		<xs:complexType>
			<xs:choice maxOccurs="unbounded">
				<xs:element ref="pii"></xs:element>
			</xs:choice>
		</xs:complexType>
	</xs:element>

	<xs:element name="pii">
		<xs:complexType>
			<xs:choice maxOccurs="unbounded">
				<xs:element ref="datas"></xs:element>
			</xs:choice>
			<xs:attribute ref="category" use="required"></xs:attribute>
		</xs:complexType>
	</xs:element>

	<xs:element name="datas">
		<xs:complexType>
			<xs:choice maxOccurs="unbounded">
				<xs:element ref="data"></xs:element>
			</xs:choice>
			<xs:attribute ref="sensitivity" use="required"></xs:attribute>
		</xs:complexType>
	</xs:element>

	<xs:element name="data">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute ref="detectionType" use="required"></xs:attribute>
					<xs:attribute name="value" type="xs:string" use="required"></xs:attribute>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<!-- IDENTITY, PERSONAL, ACCOUNT, INTERNET_AND_TELECOMMUNICATION, AUTHENTICATION_AND_AUTHORIZATION, FINANCIAL, PLACE, EDUCATION_AND_WORK, SOCIAL, MEDICAL, DEVICE_INFORMATION, OTHERS, -->
	<xs:attribute name="category">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="Personal"></xs:enumeration>
				<xs:enumeration value="Identity"></xs:enumeration>
				<xs:enumeration value="Place"></xs:enumeration>
				<xs:enumeration value="Education_And_Work"></xs:enumeration>
				<xs:enumeration value="Account"></xs:enumeration>
				<xs:enumeration value="Financial"></xs:enumeration>
				<xs:enumeration value="Authentication_And_Authorization"></xs:enumeration>
				<xs:enumeration value="Internet_And_Telecommunication"></xs:enumeration>
				<xs:enumeration value="Social"></xs:enumeration>
				<xs:enumeration value="Medical"></xs:enumeration>
				<xs:enumeration value="Device_Information"></xs:enumeration>
				<xs:enumeration value="Others"></xs:enumeration>
				<xs:enumeration value="ZOHOPII"></xs:enumeration>
			</xs:restriction>
		</xs:simpleType>
	</xs:attribute>

	<xs:attribute name="sensitivity">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="High"></xs:enumeration>
				<xs:enumeration value="Medium"></xs:enumeration>
				<xs:enumeration value="Low"></xs:enumeration>
			</xs:restriction>
		</xs:simpleType>
	</xs:attribute>

	<xs:attribute name="detectionType" type="type">
	</xs:attribute>
	
	<xs:simpleType name="type">
			<xs:restriction base="xs:string">
				<xs:enumeration value="Regex"></xs:enumeration>
				<xs:enumeration value="Dictionary"></xs:enumeration>
				<xs:enumeration value="Regex_And_Dictionary"></xs:enumeration>
				<xs:enumeration value="Machine_Learning"></xs:enumeration>
				<xs:enumeration value="Common"></xs:enumeration>
			</xs:restriction>
	</xs:simpleType>

	<xs:element name="regexes">
		<xs:complexType>
			<xs:choice maxOccurs="unbounded">
				<xs:element ref="regex"></xs:element>
			</xs:choice>
		</xs:complexType>
	</xs:element>
	<xs:element name="regex">
		<xs:complexType>
			<xs:attribute name="name" type="xs:string" use="required"></xs:attribute>
			<xs:attribute name="value" type="xs:string" use="required"></xs:attribute>
			<xs:attribute name="score" type="xs:float" use="required"></xs:attribute>
			<xs:attribute name="min-len" type="xs:decimal" use="required"></xs:attribute>
			<xs:attribute name="max-len" type="xs:decimal" use="required"></xs:attribute>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== therpraveenkumar/assessment_zoho/MickeyShopProject/AdventNetMickeyLite/AdventNet/MickeyLite/webapps/iam/conf/zsecpii-info.xml
<?xml version="1.0" encoding="UTF-8"?>
<pii-detector xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="zsecpii-info.xsd">
	<piis>
		<!-- inside the data tag attribute value is case sensitivity -->
		<pii category="Personal">
			<datas sensitivity="Medium">
				<data detectionType="Dictionary" value="PersonName" />
				<data detectionType="Machine_Learning" value="PersonML" />
				<data detectionType="Machine_Learning" value="DateML" />
				<data detectionType="Regex" value="Date" />
			</datas>
		</pii>

		<pii category="Place">
			<datas sensitivity="Medium">
				<data detectionType="Dictionary" value="Place" />
				<data detectionType="Dictionary" value="Region" />
				<data detectionType="Dictionary" value="Ethnicity" />
				<data detectionType="Dictionary" value="City" />
				<data detectionType="Dictionary" value="Country" />
				<data detectionType="Dictionary" value="CountryCode" />
				<data detectionType="Dictionary" value="Pincode" />
				<data detectionType="Machine_Learning" value="LocationML" />
			</datas>
			<datas sensitivity="Low">
				<data detectionType="Dictionary" value="State" />
			</datas>
		</pii>
		<pii category="Education_And_Work">
			<datas sensitivity="Medium">
				<data detectionType="Dictionary" value="Degree" />
				<data detectionType="Dictionary" value="Occupation" />
				<data detectionType="Dictionary" value="Org" />
				<data detectionType="Machine_Learning" value="OrganizationML" />
			</datas>
		</pii>
		<pii category="Authentication_And_Authorization">
			<datas sensitivity="High">
				<data detectionType="Regex" value="Password" />
				<!-- <data detectionType="Regex" value="Username" /> -->
			</datas>
		</pii>

		<pii category="ZOHOPII">
			<datas sensitivity="High">
				<data detectionType="Regex" value="ISCTicket/AuthenToken" />
				<data detectionType="Regex" value="IAMADT/IAMBDT" />
				<data detectionType="Regex" value="Access/RefreshToken" />
				<data detectionType="Regex" value="ISCSignature" />
				<data detectionType="Regex" value="Session_ID" />
				<data detectionType="Regex" value="ClientID" />
				<data detectionType="Regex" value="ClientToken" />
			</datas>
		</pii>
		<pii category="Identity">
			<datas sensitivity="Medium">
				<data detectionType="Regex_And_Dictionary" value="ArgentinaNationalIdentityNumber" />
				<data detectionType="Regex_And_Dictionary" value="AustraliaPassportNumber" />
				<data detectionType="Regex_And_Dictionary" value="BelgiumNationalNumber" />
				<data detectionType="Regex_And_Dictionary" value="BrazilNationalIDCard" />
				<data detectionType="Regex_And_Dictionary" value="CanadaHealthServiceNumber" />
				<data detectionType="Regex_And_Dictionary" value="CanadaPassportNumber" />
				<data detectionType="Regex_And_Dictionary" value="CanadaPersonalHealthServiceNumber" />
				<data detectionType="Regex_And_Dictionary" value="ChileIdentityCardNumber" />
				<data detectionType="Regex_And_Dictionary" value="ChinaResidentIdentityCardNumber" />
				<data detectionType="Regex_And_Dictionary" value="CrotiaIdentityCardNumber" />
				<data detectionType="Regex_And_Dictionary" value="CrotiaPersonalIdentificationNumber" />
				<data detectionType="Regex_And_Dictionary" value="CzechNationalIdentityCardNumber" />
				<data detectionType="Regex_And_Dictionary" value="DenmarkDenmarkPersonalIdentificationNumber" />
				<data detectionType="Regex_And_Dictionary" value="FinlandNationalID" />
				<data detectionType="Regex_And_Dictionary" value="FinlandPassportNumber" />
				<data detectionType="Regex_And_Dictionary" value="FranceNationalIDCardNumber" />
				<data detectionType="Regex_And_Dictionary" value="FrancePassportNumber" />
				<data detectionType="Regex_And_Dictionary" value="FranceSocialSecurityNumber" />
				<data detectionType="Regex_And_Dictionary" value="GermanyIdentityCardNumber" />
				<data detectionType="Regex_And_Dictionary" value="GermanyPassportNumber" />
				<data detectionType="Regex_And_Dictionary" value="GreeceNationalIDCard" />
				<data detectionType="Regex_And_Dictionary" value="HongkongIdentityCardNumber" />
				<data detectionType="Regex_And_Dictionary" value="IndiaAadhaar" />
				<data detectionType="Regex_And_Dictionary" value="IndiaPermanentAccountNumber" />
				<data detectionType="Regex_And_Dictionary" value="IndonesiaKTP" />
				<data detectionType="Regex_And_Dictionary" value="IrelandPPSN" />
				<data detectionType="Regex_And_Dictionary" value="IsraelNationalID" />
				<data detectionType="Regex_And_Dictionary" value="JapanPassportNumber" />
				<data detectionType="Regex_And_Dictionary" value="JapanResidentRegistrationNumber" />
				<data detectionType="Regex_And_Dictionary" value="MalaysiaIdentityCard" />
				<data detectionType="Regex_And_Dictionary" value="NetherlandsCitizenServiceNumber" />
				<data detectionType="Regex_And_Dictionary" value="NewzealandMinistryOfHealthNumber" />
				<data detectionType="Regex_And_Dictionary" value="NorwayIdentityNumber" />
				<data detectionType="Regex_And_Dictionary" value="PhilippinesUnifiedMultipurposeIDNumber" />
				<data detectionType="Regex_And_Dictionary" value="PolandIdentityCard" />
				<data detectionType="Regex_And_Dictionary" value="PolandPassport" />
				<data detectionType="Regex_And_Dictionary" value="PolandPESEL" />
				<data detectionType="Regex_And_Dictionary" value="PortugalCitizenCardNumber" />
				<data detectionType="Regex_And_Dictionary" value="SaudiarabiaNationalId" />
				<data detectionType="Regex_And_Dictionary" value="SingaporeNationalRegistrationIdentityCardNumber" />
				<data detectionType="Regex_And_Dictionary" value="SouthafricaIdentificationNumber" />
				<data detectionType="Regex_And_Dictionary" value="SouthkoreaResidentRegistrationNumber" />
				<data detectionType="Regex_And_Dictionary" value="SpainSocialSecurityNumber" />
				<data detectionType="Regex_And_Dictionary" value="SwedenNationalIDNumber" />
				<data detectionType="Regex_And_Dictionary" value="SwedenPassportNumber" />
				<data detectionType="Regex_And_Dictionary" value="TaiwanNationalID" />
				<data detectionType="Regex_And_Dictionary" value="TaiwanPassportNumber" />
				<data detectionType="Regex_And_Dictionary" value="TaiwanResidentCertificate" />
				<data detectionType="Regex_And_Dictionary" value="UkNationalHealthServiceNumber" />
				<data detectionType="Regex_And_Dictionary" value="UkPassportNumber" />
				<data detectionType="Regex_And_Dictionary" value="UsDEANumber" />
				<data detectionType="Regex_And_Dictionary" value="UsSocialSecurityNumber" />
				<data detectionType="Regex_And_Dictionary" value="BrazilLegalEntityNumber" />
			</datas>
			<datas sensitivity="Low">
				<data detectionType="Regex_And_Dictionary" value="AustraliaDriverLicenseNumber" />
				<data detectionType="Regex_And_Dictionary" value="CanadaDrivingLicenseNumber" />
				<data detectionType="Regex_And_Dictionary" value="FranceDriverLicenseNumber" />
				<data detectionType="Regex_And_Dictionary" value="GermanyDriverLicense" />
				<data detectionType="Regex_And_Dictionary" value="ItalyDriverLicenseNumber" />
				<data detectionType="Regex_And_Dictionary" value="JapanDriverLicenseNumber" />
				<data detectionType="Regex_And_Dictionary" value="UkDriverLicenseNumber" />
				<data detectionType="Regex_And_Dictionary" value="UkElectoralRollNumber" />
				<data detectionType="Regex_And_Dictionary" value="UsDriverLicenseNumber" />
			</datas>
		</pii>

		<pii category="Account">
			<datas sensitivity="Medium">
				<data detectionType="Regex_And_Dictionary" value="AustraliaMedicalAccountNumber" />
			</datas>
			<datas sensitivity="High">
				<data detectionType="Regex_And_Dictionary" value="CanadaBankAccountNumber" />
				<data detectionType="Regex_And_Dictionary" value="AustraliaBankAccountNumber" />
				<data detectionType="Regex_And_Dictionary" value="InternationalIBAN" />
				<data detectionType="Regex_And_Dictionary" value="IsraelBankAccountNumber" />
				<data detectionType="Regex_And_Dictionary" value="JapanBankAccountNumber" />
				<data detectionType="Regex_And_Dictionary" value="UsBankAccountNumber" />
			</datas>
		</pii>

		<pii category="Financial">
			<datas sensitivity="Medium">
				<data detectionType="Regex_And_Dictionary" value="BrazilCPFNumber" />
				<data detectionType="Regex_And_Dictionary" value="AustraliaTaxFileNumber" />
				<data detectionType="Regex_And_Dictionary" value="CanadaSocialInsuranceNumber" />
				<data detectionType="Regex_And_Dictionary" value="InternationalSWIFTCode" />
				<data detectionType="Regex_And_Dictionary" value="JapanSocialInsuranceNumber" />
				<data detectionType="Regex_And_Dictionary" value="UkNINO" />
				<data detectionType="Regex_And_Dictionary" value="UsABARoutingNumber" />
				<data detectionType="Regex_And_Dictionary" value="UsTaxpayerIdentificationINumber" />
			</datas>
			<datas sensitivity="High">
				<data detectionType="Regex_And_Dictionary" value="ChinaCreditCardNumber" />
				<data detectionType="Regex_And_Dictionary" value="EuDebitCard" />
				<data detectionType="Regex" value="Currency" />
				<data detectionType="Machine_Learning" value="MoneyML" />
			</datas>
		</pii>

		<pii category="Device_Information">
			<datas sensitivity="High">
				<data detectionType="Regex" value="UUID" />
				<data detectionType="Regex" value="IMEI" />
				<data detectionType="Regex" value="MAC" />
			</datas>
		</pii>

		<pii category="Internet_And_Telecommunication">
			<datas sensitivity="High">
				<data detectionType="Regex" value="Email" />
			</datas>
			<datas sensitivity="Medium">
				<data detectionType="Regex_And_Dictionary" value="InternationalIP" />
				<data detectionType="Regex" value="PhoneNumber" />
				<data detectionType="Regex" value="URL" />
			</datas>
			<datas sensitivity="Low">
				<data detectionType="Regex" value="Domain" />
			</datas>
		</pii>
		<pii category="Others">
			<datas sensitivity="Medium">
				<data detectionType="Machine_Learning" value="TimeML" />
